export default {
  categories: [
    {
      id: 1,
      name: "category1",
      image: "https://fillmurray.com/g/200/300",
    },
    {
      id: 2,
      name: "category2",
      image: "https://fillmurray.com/g/200/300",
      subcategory: "category3",
    },
    {
      id: 3,
      name: "category3",
      image: "https://fillmurray.com/g/200/300",
      subcategory: "category4",
    },
    { id: 4, name: "category4", image: "https://fillmurray.com/g/200/300" },
    {
      id: 5,
      name: "category5",
      image: "https://fillmurray.com/g/200/300",
      subcategory: "category6",
    },
    { id: 6, name: "category6", image: "https://fillmurray.com/g/200/300" },
  ],
  products: [
    {
      id: 1,
      name: "name",
      price: 100,
      image: "https://placem.at/things?w=250&random=1",
      category: "category1",
    },
    {
      id: 2,
      name: "name",
      price: 200,
      image: "https://placem.at/things?w=250&random=1",
      category: "category3",
    },
    {
      id: 3,
      name: "category1product1",
      price: 100,
      image: "https://placem.at/things?w=250&random=1",
      category: "category1",
    },
    {
      id: 4,
      name: "category1product2",
      price: 200,
      image: "https://placem.at/things?w=250&random=1",
      category: "category2",
    },
    {
      id: 5,
      name: "subcategory1product1",
      price: 100,
      image: "https://placem.at/things?w=250&random=1",
      category: "category4",
    },
    {
      id: 6,
      name: "subcategory1product2",
      price: 200,
      image: "https://placem.at/things?w=250&random=1",
      category: "category4",
    },
    {
      id: 7,
      name: "category2product1",
      price: 100,
      image: "https://placem.at/things?w=250&random=1",
      category: "category5",
    },
    {
      id: 8,
      name: "category2product2",
      price: 200,
      image: "https://placem.at/things?w=250&random=1",
    },
    {
      id: 9,
      name: "name",
      price: 100,
      image: "https://placem.at/things?w=250&random=1",
    },
    {
      id: 10,
      name: "name",
      price: 200,
      image: "https://placem.at/things?w=250&random=1",
      category: "category1",
    },
    {
      id: 11,
      name: "category1product1",
      price: 100,
      image: "https://placem.at/things?w=250&random=1",
      category: "category1",
    },
    {
      id: 12,
      name: "category1product2",
      price: 200,
      image: "https://placem.at/things?w=250&random=1",
      category: "category3",
    },
    {
      id: 13,
      name: "subcategory1product1",
      price: 100,
      image: "https://placem.at/things?w=250&random=1",
      category: "category4",
    },
    {
      id: 14,
      name: "subcategory1product2",
      price: 200,
      image: "https://placem.at/things?w=250&random=1",
      category: "category5",
    },
    {
      id: 15,
      name: "category2product1",
      price: 100,
      image: "https://placem.at/things?w=250&random=1",
      category: "category6",
    },
    {
      id: 16,
      name: "category2product2",
      price: 200,
      image: "https://placem.at/things?w=250&random=1",
      category: "category2",
    },
  ],
};
